version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "5000:5000"
    environment:
      - PORT_NUMBER=5050 # Replace with your environment variables if needed
