#cloud-config

users:
  - default
  - name: kubernetes
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    shell: /bin/bash
    password: "parola"
    chpasswd: { expire: False }
    ssh_pwauth: True
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDC+TIRddJ+aN5p4H8maa4aKCdsJRMGEtggzsHSOPKBWnwkbMhw4jawphyj/aNDPG5mW3I6hA1g6DmccscYILlza3fuY/evkdkp04MpQ/4W1mv64cUjhHdE6ofDrIt9suMEAXUPfCosmDL84NckF4iaWMbyDV/75sPxDSQmm1zExAj0oUfROTzOjd+7bo1DhhvrYoB9c+TbS54hwui6PHfHezKaJvvHPmM7rIxtOoC7BdS7JfxBVg9Ahcds5nPNQHcm6ZcY++/KilydQ4VaT5Gr4BNk8QGdvvu51Uk5fgzLGd7izGcGW2n7PxarccYsZNqdW/hwyvjFbjj1kuZYHMtoobaYq2Cn+0rM6p/zkmemvuFCzPlL+jNDeuMGfzjhfP7oWw+VhogQNVS9R707e60Kgo4rWzyusTuvlmEWyicD7wfwolROTt5Z4qoIbq+oaQixo6CK9qWScJ6159QR3Rk2f1j6KmAde3k/d7un/VPJCQY39qzOpvZrAg471UglcOAWAPYsfi4LcoOPUPBv/nJnA0kPpdnOSX9E329qIN6TX0sHGXBCTELmv/4CT0HQIFodxUyJG+qLIUmRa/IsgRmcrirP4p1t1nuVRDtTgFoyqU8Zu5raEyBfRpgAMUlpatzOL/T+EAL/mSlm1HN+279WUvjTx5i/sz1IC8TUwL/c8w== darius@darius-ROG-Flow-X13-GV301RC-GV301RC

hostname: k8s-node-master
preserve_hostname: false

network:
  version: 2
  renderer: networkd
  ethernets:
    cluster0:
      match:
        macaddress: "52:54:00:b0:be:7d"
      set-name: eth-cluster
      dhcp4: false
      addresses:
        - 172.16.100.3/29
      gateway4: 172.16.100.1
      nameservers:
        addresses:
          - 8.8.8.8
          - 8.8.4.4
    mgmt0:
      match:
        macaddress: "52:54:00:51:e6:d6"
      set-name: eth-mgmt
      dhcp4: true

packages:
  - qemu-guest-agent
  - curl
  - apt-transport-https
  - ca-certificates

runcmd:
  - sed -i 's/GRUB_CMDLINE_LINUX="/GRUB_CMDLINE_LINUX="console=ttyS0,115200 console=tty1 /' /etc/default/grub
  - update-grub
  - systemctl enable --now serial-getty@ttyS0.service
  - systemctl enable --now qemu-guest-agent
  - dhclient -v ens3
  - apt update
  - apt install docker.io -y
  - curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
  - echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.30/deb/ /' | sudo tee /etc/apt/sources.list.d/kubernetes.list
  - apt update
  - apt install kubeadm kubelet kubectl -y
  - apt-mark hold kubeadm kubelet kubectl
  - kubeadm version
  - echo "finished" > /home/kubernetes/finished.txt
  # - apt install docker.io
  # - curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.32/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
  # - echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.32/deb/ /' | sudo tee /etc/apt/sources.list.d/kubernetes.list
  # - apt-get update
  # - apt-get install -y kubelet kubeadm kubectl kubernetes-cni
  # - apt-mark hold kubelet kubeadm kubectl
  # - systemctl enable --now kubelet
  # - until systemctl is-active --quiet containerd; do sleep 2; done
  # - echo "waiting for containerd to be active..."
  # - sleep 30
  # - until systemctl is-active --quiet kubelet; do sleep 2; done
  # - echo "waiting for kubelet to be active..."
  # - sleep 10
  # - MASTER_IP=$(hostname -I | awk '{print $1}')
  # - echo "starting kubeadm init with api server address $MASTER_IP"
  # - kubeadm init --pod-network-cidr=192.168.1.0/16 --apiserver-advertise-address=$MASTER_IP > /root/kubeadm-init.log
  # - until curl -k --silent http://127.0.0.1:2381/readyz | grep -q 'ok'; do sleep 2; done
  # - mkdir -p /home/kubernetes/.kube
  # - cp -i /etc/kubernetes/admin.conf /home/kubernetes/.kube/config
  # - chown kubernetes:kubernetes /home/kubernetes/.kube/config
  # - echo "export KUBECONFIG=/home/kubernetes/.kube/config" >> /home/kubernetes/.bashrc
  # - kubeadm token create --print-join-command > /root/kubead./m-join.sh