#cloud-config

users:
  - default
  - name: kubernetes
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    shell: /bin/bash
    password: "parola"
    chpasswd: { expire: False }
    ssh_pwauth: True
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDQg+bgKjO2udAxGhBDnHWdoo7c/U1jcQNELNr7Ofk2RhMI1Xfk/o6NPvniGCLGbjxliq0xqMHfMCP6Q5FL88ryfyY/LRJQtykOrcIPtdod3BFpGzN/SVI/H+ESgHfNr96KiJybX9yzUKZCiv/01DMPGgko0cx99Tl5npl7ZGKO7ZRZB87ejiRylqTQybnnpzB9Rw69huwcrO8mSZ6yMFRFXillmyzLSgm33VuJvJioOijz7Hxa0o/jyn6QdIc5xReyLHCCrOKKDTtc8QglQrHNGpWZOl3iLgcXOG5HLj84zDT022GOpS7yRQ/Jt9HLy9sY94xiE70bR4k5apvm/jz7RNm61eFyl4hhcrguv2bS5vHD2ee2E9zukDFbqBZGGuW4B1oPvX4PorHSxSPkoL2KsdlFwPEXelyth5N8aA+HQPp8r0WNo/Y0fJ4t+a2TwB9BJwWGoJ5US8fPNjmg6CoBZ8OiIJD/AGjBAXvpbLT+QczVDGCcaOWM32dOiQTf8JdNFhwrMxBV7SWlJxJFrGT2/L0LmmicbQastJ31UGGXJwislSCd0w/tm/iN3wXx19betXw2K7gkwlLvtWtlmbSdKowql3jIF9Qme9JE0HzJ3wYnzfdQR89q4W9pTzm3Fv1xJQQJntFe+CkVXACEf+jcRQHrR17uYKK0ta+EiM+4LQ== darius@darius-ROG-Flow-X13-GV301RC-GV301RC

hostname: k8s-node-master
preserve_hostname: false

network:
  version: 2
  ethernets:
    ens3:
      dhcp4: true
      addresses:
        - 192.168.122.100/24
      gateway4: 192.168.122.1
      nameservers:
        addresses:
          - 8.8.8.8
          - 8.8.4.4

packages:
  - qemu-guest-agent
  - curl
  - apt-transport-https
  - ca-certificates

runcmd:
  - systemctl enable --now qemu-guest-agent
  - dhclient -v ens3
  - apt update
  - apt install docker.io -y
  - curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
  - echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.30/deb/ /' | sudo tee /etc/apt/sources.list.d/kubernetes.list
  - apt update
  - apt install kubeadm kubelet kubectl -y
  - apt-mark hold kubeadm kubelet kubectl
  - kubeadm version
  - echo "finished" > /home/kubernetes/finished.txt
  # - apt install docker.io
  # - curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.32/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
  # - echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.32/deb/ /' | sudo tee /etc/apt/sources.list.d/kubernetes.list
  # - apt-get update
  # - apt-get install -y kubelet kubeadm kubectl kubernetes-cni
  # - apt-mark hold kubelet kubeadm kubectl
  # - systemctl enable --now kubelet
  # - until systemctl is-active --quiet containerd; do sleep 2; done
  # - echo "waiting for containerd to be active..."
  # - sleep 30
  # - until systemctl is-active --quiet kubelet; do sleep 2; done
  # - echo "waiting for kubelet to be active..."
  # - sleep 10
  # - MASTER_IP=$(hostname -I | awk '{print $1}')
  # - echo "starting kubeadm init with api server address $MASTER_IP"
  # - kubeadm init --pod-network-cidr=192.168.1.0/16 --apiserver-advertise-address=$MASTER_IP > /root/kubeadm-init.log
  # - until curl -k --silent http://127.0.0.1:2381/readyz | grep -q 'ok'; do sleep 2; done
  # - mkdir -p /home/kubernetes/.kube
  # - cp -i /etc/kubernetes/admin.conf /home/kubernetes/.kube/config
  # - chown kubernetes:kubernetes /home/kubernetes/.kube/config
  # - echo "export KUBECONFIG=/home/kubernetes/.kube/config" >> /home/kubernetes/.bashrc
  # - kubeadm token create --print-join-command > /root/kubead./m-join.sh