#cloud-config

users:
  - default
  - name: kubernetes
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    shell: /bin/bash
    passwd: $6$rounds=4096$ZMReQfwhYfCWjz01$qdcmo5KGuMBWEzA.uSWnOI9NYC0nKpPvGQuWpeEvOVydAs5YFZDoPRXJ8vJCSGHyys4Ji6pCEJ.QwnHO0OJod0
    lock_passwd: Optional
    chpasswd: { expire: False }
    ssh_pwauth: True
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDM0cwFbSw+oKjom7TtA/3QZGWY3595SllAV2fQmCyuy+tgv802TPDcFAAqyg9eVZDVhB1HJYY1aHmbH+wTd7irDFLxc5WzjzUSN3VzJCSno6XQhc8BLzAQKz1U6I+785k9tZV/nEiV2JoqDcBIMK5MykZRESMQenvsj/sD2SM2O2K3KdvPElcV046InbduB+AbGdfbFd5h29Nmmrzn3bXZ53HbBckIwYEFkhfn6wWScifgAOJ0Pn+Li5O5uinGxmf+d6wn0pga8R79gXpOh51kDD5eOTLZHvavra5eTeubHvpr8hX4wFRfAWb0+wj0iVXRQgNVaXS+BQDsuBmD1fK3tRSauJ49vRIWDepdRKKUDCFOZ9nPKgjV5zZBuvKnIF8Q4P78EDxUZszpwswn+CaAtk31aAUEmT1CRQ50TDFu9qUxy9Kq5ng8pQmlBFPGF3CjOLYTFukHw1U21kVKEu7cYRAMGiV4Rt3GvMyxi2h0rWyVp/qar2MtS9TskMsFx0Z4S++vwFqCBd64D+wDwUUQkoN+KD+m+JS+NP0ouK1fJOiEguAYLMq5/Ec4U2o1aqXAkr7E39e5at+l9g4eM+Ziw1L+hMNHi9Bncau2bfUWfx4mkemxgFlTz1fw2RQvCBsiRd59cEMcy5bVgFElQrFIbGKChjMfrjPIeQe+RkoL6w== darius@darius-ROG-Flow-X13-GV301RC-GV301RC

hostname: k8s-node-worker2
preserve_hostname: false

network:
  version: 2
  ethernets:
    ens3:
      dhcp4: true
      addresses:
        - 192.168.122.100/24
      gateway4: 192.168.122.1
      nameservers:
        addresses:
          - 8.8.8.8
          - 8.8.4.4

packages:
  - qemu-guest-agent
  - curl
  - apt-transport-https
  - ca-certificates
  - containerd

runcmd:
  - apt install -y wireguard
  - systemctl enable --now qemu-guest-agent
  - dhclient -v ens3
  - apt update
  - apt install docker.io -y
  - curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
  - echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.30/deb/ /' | sudo tee /etc/apt/sources.list.d/kubernetes.list
  - apt update
  - apt install kubeadm kubelet kubectl -y
  - apt-mark hold kubeadm kubelet kubectl
  - kubeadm version
  - mkdir -p /etc/wireguard
  - wg genkey | tee /etc/wireguard/private.key | wg pubkey > /home/kubernetes/wg.pub
  - chmod 600 /etc/wireguard/private.key
  - chown kubernetes:kubernetes /etc/wireguard/wg.pub
  - echo "finished" > /home/kubernetes/finished.txt
  # - curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.32/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
  # - echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.32/deb/ /' | sudo tee /etc/apt/sources.list.d/kubernetes.list
  # - apt-get update
  # - apt-get install -y kubelet kubeadm kubectl kubernetes-cni
  # - sudo apt-mark hold kubelet kubeadm kubectl
  # - systemctl enable --now kubelet
  # - echo "waiting for master to be ready..."
  # - until [ -f /root/kubeadm-join.sh ]; do sleep 5; done
  # - chmod +x /root/kubeadm-join.sh
  # - bash /root/kubeadm-join.sh