#cloud-config

users:
  - default
  - name: kubernetes
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    shell: /bin/bash
    password: "parola"
    chpasswd: { expire: False }
    ssh_pwauth: True
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDC+TIRddJ+aN5p4H8maa4aKCdsJRMGEtggzsHSOPKBWnwkbMhw4jawphyj/aNDPG5mW3I6hA1g6DmccscYILlza3fuY/evkdkp04MpQ/4W1mv64cUjhHdE6ofDrIt9suMEAXUPfCosmDL84NckF4iaWMbyDV/75sPxDSQmm1zExAj0oUfROTzOjd+7bo1DhhvrYoB9c+TbS54hwui6PHfHezKaJvvHPmM7rIxtOoC7BdS7JfxBVg9Ahcds5nPNQHcm6ZcY++/KilydQ4VaT5Gr4BNk8QGdvvu51Uk5fgzLGd7izGcGW2n7PxarccYsZNqdW/hwyvjFbjj1kuZYHMtoobaYq2Cn+0rM6p/zkmemvuFCzPlL+jNDeuMGfzjhfP7oWw+VhogQNVS9R707e60Kgo4rWzyusTuvlmEWyicD7wfwolROTt5Z4qoIbq+oaQixo6CK9qWScJ6159QR3Rk2f1j6KmAde3k/d7un/VPJCQY39qzOpvZrAg471UglcOAWAPYsfi4LcoOPUPBv/nJnA0kPpdnOSX9E329qIN6TX0sHGXBCTELmv/4CT0HQIFodxUyJG+qLIUmRa/IsgRmcrirP4p1t1nuVRDtTgFoyqU8Zu5raEyBfRpgAMUlpatzOL/T+EAL/mSlm1HN+279WUvjTx5i/sz1IC8TUwL/c8w== darius@darius-ROG-Flow-X13-GV301RC-GV301RC

hostname: k8s-node-master
preserve_hostname: false

packages:
  - qemu-guest-agent
  - curl
  - apt-transport-https
  - ca-certificates
  - containerd

runcmd:
  - systemctl enable --now qemu-guest-agent
  - dhclient -v ens3
  - apt update
  - apt install docker.io -y
  - curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
  - echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.30/deb/ /' | sudo tee /etc/apt/sources.list.d/kubernetes.list
  - apt update
  - apt install kubeadm kubelet kubectl -y
  - apt-mark hold kubeadm kubelet kubectl
  - kubeadm version
  - echo "finished" > /home/kubernetes/finished.txt