version: 2
renderer: networkd
ethernets:
  enp1s0:
    dhcp4: false
    addresses: [172.16.100.3/29]
    gateway4: 172.16.100.2
    nameservers:
      addresses: [8.8.8.8,8.8.4.4]
    optional: false
  enp2s0:
    dhcp4: true
    gateway4: 192.168.122.1
    nameservers:
      addresses:
        - 8.8.8.8
        - 8.8.4.4
    link-local: []
    optional: false
    

