apiVersion: apps/v1
kind: Deployment
metadata:
  name: testing-app
  labels:
    app: testing-app
spec:
  replicas: REPLICA_NUMBER
  # Replace REPLICA_NUMBER with the desired number of replicas
  selector:
    matchLabels:
      app: testing-app
  template:
    metadata:
      labels:
        app: testing-app
    spec:
      containers:
        - name: testing-app
          image: ghercadarius/testapp:latest
          ports:
            - containerPort: 5000
