apiVersion: v1
kind: Service
metadata:
  name: node-exporter
spec:
  type: NodePort
  selector:
    app: node-exporter
  ports:
    - protocol: TCP
      port: 9100           # Port *inside* the cluster
      targetPort: 9100     # Port your pod listens on
      nodePort: 30081      # Port on the node's IP (must be 30000-32767, or leave blank for auto)
