version: 2
renderer: networkd
ethernets:
  enp1s0:
    dhcp4: false
    addresses: [172.16.100.4/29]
    gateway4: 172.16.100.1
    optional: false
  enp2s0:
    dhcp4: true
    gateway4: 192.168.122.1
    link-local: []
    optional: false
    